### PR TITLE
Add removal instructions for (boring people)

### PR DESCRIPTION
**Pull request by wannafedora**

### CODE REVIEW

**Review by LuanderFarias — APPROVED** [review]

**Comment by LuanderFarias** [comment]
Looks Nice!! tysm :)

**Comment by wannafedor4** [comment]
@LuanderFarias hi. I was the ghost in this pull (not lying, clone the repo and check this pull.) thanks for merging this. it was my first pull request ever!

**Comment by LuanderFarias** [comment]
> @LuanderFarias hi. I was the ghost in this pull (not lying, clone the repo and check this pull.) thanks for merging this. it was my first pull request ever!

NO PROBLEM! Great you were able to get your first contribution through here :)

**Comment by wannafedor4** [comment]
> > @LuanderFarias hi. I was the ghost in this pull (not lying, clone the repo and check this pull.) thanks for merging this. it was my first pull request ever!
> 
> NO PROBLEM! Great you were able to get your first contribution through here :)

yep!
btw im going to be a mac user as of december 26 but I'll see what features I can bring from mac arc!

**Comment by LuanderFarias** [comment]
> > > @LuanderFarias hi. I was the ghost in this pull (not lying, clone the repo and check this pull.) thanks for merging this. it was my first pull request ever!
> > 
> > NO PROBLEM! Great you were able to get your first contribution through here :)
> 
> yep!
> btw im going to be a mac user as of december 26 but I'll see what features I can bring from mac arc!

NICE, sorry for the arcfox being so abandoned lol. Hope everything goes fine with arc :3

**Pull request merged**
